// Quick reference for nursing students (adult values unless noted). Ranges differ slightly between labs and textbooks.
export const REF = [
  {
    id: "lab", he: "ערכי מעבדה", en: "Lab values",
    rows: [
      ["נתרן (Na)", "Sodium (Na)", "135–145 mEq/L"],
      ["אשלגן (K)", "Potassium (K)", "3.5–5.0 mEq/L"],
      ["כלוריד (Cl)", "Chloride (Cl)", "98–106 mEq/L"],
      ["סידן כללי (Ca)", "Total calcium (Ca)", "8.5–10.5 mg/dL"],
      ["מגנזיום (Mg)", "Magnesium (Mg)", "1.7–2.2 mg/dL"],
      ["גלוקוז בצום", "Fasting glucose", "70–100 mg/dL"],
      ["HbA1c", "HbA1c", "< 5.7%"],
      ["שתנן (BUN)", "BUN", "7–20 mg/dL"],
      ["קריאטינין", "Creatinine", "0.6–1.2 mg/dL"],
      ["אלבומין", "Albumin", "3.5–5.0 g/dL"],
      ["המוגלובין – גברים", "Hemoglobin – men", "14–18 g/dL"],
      ["המוגלובין – נשים", "Hemoglobin – women", "12–16 g/dL"],
      ["המטוקריט – גברים", "Hematocrit – men", "42–52%"],
      ["המטוקריט – נשים", "Hematocrit – women", "37–47%"],
      ["כדוריות לבנות (WBC)", "White cells (WBC)", "4,500–11,000 /mm³"],
      ["טסיות", "Platelets", "150,000–400,000 /mm³"],
      ["INR (ללא טיפול)", "INR (no anticoagulant)", "0.8–1.1"],
      ["INR בטיפול בוורפרין", "INR on warfarin", "2–3 (usually)"],
      ["aPTT", "aPTT", "30–40 sec"],
      ["דיגוקסין (רמה טיפולית)", "Digoxin (therapeutic)", "0.5–2.0 ng/mL"],
      ["ליתיום (רמה טיפולית)", "Lithium (therapeutic)", "0.6–1.2 mEq/L"],
    ],
  },
  {
    id: "abg", he: "גזים בדם", en: "Blood gases",
    rows: [
      ["pH", "pH", "7.35–7.45"],
      ["PaCO₂", "PaCO₂", "35–45 mmHg"],
      ["HCO₃⁻", "HCO₃⁻", "22–26 mEq/L"],
      ["PaO₂", "PaO₂", "80–100 mmHg"],
      ["SaO₂", "SaO₂", "95–100%"],
      ["pH נמוך + PaCO₂ גבוה", "Low pH + high PaCO₂", "Respiratory acidosis"],
      ["pH נמוך + HCO₃⁻ נמוך", "Low pH + low HCO₃⁻", "Metabolic acidosis"],
      ["pH גבוה + PaCO₂ נמוך", "High pH + low PaCO₂", "Respiratory alkalosis"],
      ["pH גבוה + HCO₃⁻ גבוה", "High pH + high HCO₃⁻", "Metabolic alkalosis"],
    ],
  },
  {
    id: "vitals", he: "סימנים חיוניים", en: "Vital signs",
    rows: [
      ["דופק – מבוגר", "Heart rate – adult", "60–100 /min"],
      ["נשימות – מבוגר", "Respirations – adult", "12–20 /min"],
      ["לחץ דם תקין – מבוגר", "Normal BP – adult", "< 120/80 mmHg"],
      ["חום (פה)", "Temperature (oral)", "36.5–37.5 °C"],
      ["סטורציה", "SpO₂", "95–100%"],
      ["דופק – יילוד", "Heart rate – newborn", "120–160 /min"],
      ["נשימות – יילוד", "Respirations – newborn", "30–60 /min"],
      ["תפוקת שתן מינימלית – מבוגר", "Minimum urine output – adult", "0.5 mL/kg/h (≈30 mL/h)"],
      ["גלזגו (GCS)", "Glasgow (GCS)", "3–15 · E4 V5 M6 · ≤ 8 = severe"],
    ],
  },
  {
    id: "formulas", he: "נוסחאות", en: "Formulas",
    rows: [
      ["מינון", "Dose", "(Desired ÷ Have) × Volume"],
      ["קצב טפטוף", "Drip rate (gtt/min)", "Volume (mL) × drop factor ÷ time (min)"],
      ["משאבה", "Pump (mL/h)", "Volume (mL) ÷ time (h)"],
      ["מינון לפי משקל", "Weight-based dose", "mg/kg × weight (kg)"],
      ["לחץ עורקי ממוצע", "MAP", "(SBP + 2 × DBP) ÷ 3"],
      ["BMI", "BMI", "weight (kg) ÷ height² (m)"],
      ["פרקלנד (כוויות)", "Parkland (burns)", "4 mL × kg × %TBSA · ½ in first 8 h"],
    ],
  },
  {
    id: "conv", he: "המרות", en: "Conversions",
    rows: [
      ["1 ק״ג", "1 kg", "2.2 lb"],
      ["1 גרם", "1 g", "1,000 mg"],
      ["1 מ״ג", "1 mg", "1,000 mcg"],
      ["1 ליטר", "1 L", "1,000 mL"],
      ["כפית", "1 teaspoon", "5 mL"],
      ["כף", "1 tablespoon", "15 mL"],
      ["1 אונקיה", "1 oz", "30 mL"],
      ["°F ← °C", "°C → °F", "°F = °C × 9/5 + 32"],
      ["°C ← °F", "°F → °C", "°C = (°F − 32) × 5/9"],
    ],
  },
];
